### ISSUE TITLE
docker-registry-driver-swift uninstallable.

### ISSUE THREAD

**Issue by pschwartz** [bacongobbler/docker-registry-driver-swift#25] opened 2015-02-05 00:58 UTC
Currently there appears to be an issue with the official ubuntu:14.04 image causing the following error.

OSError: [Errno 39] Directory not empty: '/tmp/pip-*'

You usually see this on the attempt to install python-keystoneclient when it attempts to update six from version 1.5.2 to 1.9.0.

The error produced is the same when doing the install of the swift driver in the registry container or using the Dockerfile in the drivers repo.

This issue is most likely not directly related to the driver, but something that changed in the base ubuntu:14.04 image used in the registry image.

**Comment by bacongobbler** [comment] 2015-02-06 23:36
Seems to work fine for me on master:

```
><> cd docker-registry-driver-swift
><> docker build .
Sending build context to Docker daemon 132.1 kB
Sending build context to Docker daemon
Step 0 : FROM registry
registry:latest: The image you are pulling has been verified

27d47432a69b: Pull complete
5f92234dcf1e: Pull complete
51a9c7c1f8bb: Pull complete
5ba9dab47459: Pull complete
30e25c7b70df: Pull complete
ed34dec80489: Pull complete
0e7a483810f6: Pull complete
eaebc036889a: Pull complete
8ec695ba9240: Pull complete
ecc59b06f5b7: Pull complete
63ad05f3af00: Pull complete
f054bc98768f: Pull complete
214c09aed08b: Pull complete
c55308716b36: Pull complete
511136ea3c5a: Already exists
Status: Downloaded newer image for registry:latest
 ---> c55308716b36
Step 1 : MAINTAINER Matthew Fisher <me@bacongobbler.com>
 ---> Running in b8b8ab5b77a3
 ---> f26303635ddd
Removing intermediate container b8b8ab5b77a3
Step 2 : RUN apt-get update && apt-get install -yq python-lxml
 ---> Running in 38e69fa7751b
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Get:1 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:2 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Get:3 http://archive.ubuntu.com trusty-security Release.gpg [933 B]
Get:4 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:5 http://archive.ubuntu.com trusty-updates Release [62.0 kB]
Get:6 http://archive.ubuntu.com trusty-security Release [62.0 kB]
Get:7 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:8 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:9 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:10 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:11 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:12 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:13 http://archive.ubuntu.com trusty-updates/main Sources [208 kB]
Get:14 http://archive.ubuntu.com trusty-updates/restricted Sources [1874 B]
Get:15 http://archive.ubuntu.com trusty-updates/universe Sources [124 kB]
Get:16 http://archive.ubuntu.com trusty-updates/main amd64 Packages [524 kB]
Get:17 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [14.8 kB]
Get:18 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [318 kB]
Get:19 http://archive.ubuntu.com trusty-security/main Sources [79.8 kB]
Get:20 http://archive.ubuntu.com trusty-security/restricted Sources [1874 B]
Get:21 http://archive.ubuntu.com trusty-security/universe Sources [19.1 kB]
Get:22 http://archive.ubuntu.com trusty-security/main amd64 Packages [251 kB]
Get:23 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.8 kB]
Get:24 http://archive.ubuntu.com trusty-security/universe amd64 Packages [110 kB]
Fetched 20.5 MB in 35s (574 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libxml2 libxslt1.1 sgml-base xml-core
Suggested packages:
  python-lxml-dbg sgml-base-doc debhelper
The following NEW packages will be installed:
  libxml2 libxslt1.1 python-lxml sgml-base xml-core
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 1380 kB of archives.
After this operation, 5191 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libxml2 amd64 2.9.1+dfsg1-3ubuntu4.4 [570 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main sgml-base all 1.26+nmu4ubuntu1 [12.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main xml-core all 0.13+nmu2 [23.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-lxml amd64 3.3.3-1ubuntu0.1 [629 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Fetched 1380 kB in 3s (370 kB/s)
Selecting previously unselected package libxml2:amd64.
(Reading database ... 20475 files and directories currently installed.)
Preparing to unpack .../libxml2_2.9.1+dfsg1-3ubuntu4.4_amd64.deb ...
Unpacking libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.4) ...
Selecting previously unselected package sgml-base.
Preparing to unpack .../sgml-base_1.26+nmu4ubuntu1_all.deb ...
Unpacking sgml-base (1.26+nmu4ubuntu1) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2build1) ...
Selecting previously unselected package xml-core.
Preparing to unpack .../xml-core_0.13+nmu2_all.deb ...
Unpacking xml-core (0.13+nmu2) ...
Selecting previously unselected package python-lxml.
Preparing to unpack .../python-lxml_3.3.3-1ubuntu0.1_amd64.deb ...
Unpacking python-lxml (3.3.3-1ubuntu0.1) ...
Setting up libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.4) ...
Setting up sgml-base (1.26+nmu4ubuntu1) ...
Setting up libxslt1.1:amd64 (1.1.28-2build1) ...
Setting up xml-core (0.13+nmu2) ...
Setting up python-lxml (3.3.3-1ubuntu0.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
 ---> ca72d1c58e6b
Removing intermediate container 38e69fa7751b
Step 3 : COPY . /src
 ---> de911e6daf3d
Removing intermediate container ef7c44c5a898
Step 4 : RUN pip install /src
 ---> Running in 544fec4eab29
Unpacking /src
  Running setup.py (path:/tmp/pip-8cnMuB-build/setup.py) egg_info for package from file:///src

Requirement already satisfied (use --upgrade to upgrade): docker-registry-core>=2,<3 in /usr/local/lib/python2.7/dist-packages (from docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking python-keystoneclient==0.10.0 (from docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking python-swiftclient==2.2.0 (from docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): boto==2.34.0 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): redis==2.10.3 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): setuptools==5.8 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): simplejson==3.6.2 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking iso8601>=0.1.9 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading iso8601-0.1.10.tar.gz
  Running setup.py (path:/tmp/pip_build_root/iso8601/setup.py) egg_info for package iso8601

Requirement already satisfied (use --upgrade to upgrade): requests>=1.1 in /usr/local/lib/python2.7/dist-packages (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking stevedore>=0.14 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading stevedore-1.2.0-py2.py3-none-any.whl
Downloading/unpacking Babel>=1.3 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Running setup.py (path:/tmp/pip_build_root/Babel/setup.py) egg_info for package Babel

    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.3 in /usr/lib/python2.7/dist-packages (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking six>=1.7.0 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking netaddr>=0.7.6 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking oslo.config>=1.2.1 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking pbr>=0.6,!=0.7,<1.0 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking PrettyTable>=0.7,<0.8 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading prettytable-0.7.2.tar.bz2
  Running setup.py (path:/tmp/pip_build_root/PrettyTable/setup.py) egg_info for package PrettyTable

Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking pytz>=0a (from Babel>=1.3->python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/lib/python2.7/dist-packages (from pbr>=0.6,!=0.7,<1.0->python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Installing collected packages: python-keystoneclient, python-swiftclient, docker-registry-driver-swift, iso8601, stevedore, Babel, six, netaddr, oslo.config, pbr, PrettyTable, pytz
  Running setup.py install for docker-registry-driver-swift
    Skipping installation of /usr/local/lib/python2.7/dist-packages/docker_registry/__init__.py (namespace package)
    Skipping installation of /usr/local/lib/python2.7/dist-packages/docker_registry/drivers/__init__.py (namespace package)

    Installing /usr/local/lib/python2.7/dist-packages/docker_registry_driver_swift-0.2.1_git-py2.7-nspkg.pth
  Running setup.py install for iso8601

  Running setup.py install for Babel

    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    Installing pybabel script to /usr/local/bin
  Found existing installation: six 1.5.2
    Uninstalling six:
      Successfully uninstalled six
  Running setup.py install for PrettyTable

Successfully installed python-keystoneclient python-swiftclient docker-registry-driver-swift iso8601 stevedore Babel six netaddr oslo.config pbr PrettyTable pytz
Cleaning up...
 ---> b923cd6ee052
Removing intermediate container 544fec4eab29
Successfully built b923cd6ee052
```

Are you using the root Dockerfile to build the registry w/ swift driver support, or some other user's image?

**Comment by pschwartz** [comment] 2015-02-06 23:47
I have tried from 4 different systems.

This was a clean pull of master at 6:40pm EST.
```
core@core-01 ~ $ git clone https://github.com/bacongobbler/docker-registry-driver-swift    
Cloning into 'docker-registry-driver-swift'...
remote: Counting objects: 212, done.
remote: Total 212 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (212/212), 40.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (96/96), done.
Checking connectivity... done.
core@core-01 ~ $ cd docker-registry-driver-swift/
core@core-01 ~/docker-registry-driver-swift $ docker build .
Sending build context to Docker daemon 132.1 kB
Sending build context to Docker daemon 
Step 0 : FROM registry
registry:latest: The image you are pulling has been verified
27d47432a69b: Pull complete 
5f92234dcf1e: Pull complete 
51a9c7c1f8bb: Pull complete 
5ba9dab47459: Pull complete 
30e25c7b70df: Pull complete 
ed34dec80489: Pull complete 
0e7a483810f6: Pull complete 
eaebc036889a: Pull complete 
8ec695ba9240: Pull complete 
ecc59b06f5b7: Pull complete 
63ad05f3af00: Pull complete 
f054bc98768f: Pull complete 
214c09aed08b: Pull complete 
c55308716b36: Pull complete 
511136ea3c5a: Already exists 
Status: Downloaded newer image for registry:latest
 ---> c55308716b36
Step 1 : MAINTAINER Matthew Fisher <me@bacongobbler.com>
 ---> Running in 4ac7a67eae0b
 ---> ac31297e2cbb
Removing intermediate container 4ac7a67eae0b
Step 2 : RUN apt-get update && apt-get install -yq python-lxml
 ---> Running in edd0f68d9cc1
Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.ubuntu.com trusty-updates InRelease
Ign http://archive.ubuntu.com trusty-security InRelease
Get:1 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:2 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
Get:3 http://archive.ubuntu.com trusty-security Release.gpg [933 B]
Get:4 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:5 http://archive.ubuntu.com trusty-updates Release [62.0 kB]
Get:6 http://archive.ubuntu.com trusty-security Release [62.0 kB]
Get:7 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:8 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:9 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:10 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:11 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:12 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Get:13 http://archive.ubuntu.com trusty-updates/main Sources [208 kB]
Get:14 http://archive.ubuntu.com trusty-updates/restricted Sources [1874 B]
Get:15 http://archive.ubuntu.com trusty-updates/universe Sources [124 kB]
Get:16 http://archive.ubuntu.com trusty-updates/main amd64 Packages [524 kB]
Get:17 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [14.8 kB]
Get:18 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [318 kB]
Get:19 http://archive.ubuntu.com trusty-security/main Sources [79.8 kB]
Get:20 http://archive.ubuntu.com trusty-security/restricted Sources [1874 B]
Get:21 http://archive.ubuntu.com trusty-security/universe Sources [19.1 kB]
Get:22 http://archive.ubuntu.com trusty-security/main amd64 Packages [251 kB]
Get:23 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [14.8 kB]
Get:24 http://archive.ubuntu.com trusty-security/universe amd64 Packages [110 kB]
Fetched 20.5 MB in 6s (2974 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libxml2 libxslt1.1 sgml-base xml-core
Suggested packages:
  python-lxml-dbg sgml-base-doc debhelper
The following NEW packages will be installed:
  libxml2 libxslt1.1 python-lxml sgml-base xml-core
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 1380 kB of archives.
After this operation, 5191 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libxml2 amd64 2.9.1+dfsg1-3ubuntu4.4 [570 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty/main sgml-base all 1.26+nmu4ubuntu1 [12.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libxslt1.1 amd64 1.1.28-2build1 [145 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main xml-core all 0.13+nmu2 [23.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-lxml amd64 3.3.3-1ubuntu0.1 [629 kB]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 1380 kB in 0s (1745 kB/s)
Selecting previously unselected package libxml2:amd64.
(Reading database ... 20475 files and directories currently installed.)
Preparing to unpack .../libxml2_2.9.1+dfsg1-3ubuntu4.4_amd64.deb ...
Unpacking libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.4) ...
Selecting previously unselected package sgml-base.
Preparing to unpack .../sgml-base_1.26+nmu4ubuntu1_all.deb ...
Unpacking sgml-base (1.26+nmu4ubuntu1) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../libxslt1.1_1.1.28-2build1_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2build1) ...
Selecting previously unselected package xml-core.
Preparing to unpack .../xml-core_0.13+nmu2_all.deb ...
Unpacking xml-core (0.13+nmu2) ...
Selecting previously unselected package python-lxml.
Preparing to unpack .../python-lxml_3.3.3-1ubuntu0.1_amd64.deb ...
Unpacking python-lxml (3.3.3-1ubuntu0.1) ...
Setting up libxml2:amd64 (2.9.1+dfsg1-3ubuntu4.4) ...
Setting up sgml-base (1.26+nmu4ubuntu1) ...
Setting up libxslt1.1:amd64 (1.1.28-2build1) ...
Setting up xml-core (0.13+nmu2) ...
Setting up python-lxml (3.3.3-1ubuntu0.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.5) ...
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
 ---> bd89c65571e9
Removing intermediate container edd0f68d9cc1
Step 3 : COPY . /src
 ---> 318f996b2666
Removing intermediate container 054487117bdc
Step 4 : RUN pip install /src
 ---> Running in b8d458605777
Unpacking /src
  Running setup.py (path:/tmp/pip-XXWtaW-build/setup.py) egg_info for package from file:///src
    
Requirement already satisfied (use --upgrade to upgrade): docker-registry-core>=2,<3 in /usr/local/lib/python2.7/dist-packages (from docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking python-keystoneclient==0.10.0 (from docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking python-swiftclient==2.2.0 (from docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): boto==2.34.0 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): redis==2.10.3 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): setuptools==5.8 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): simplejson==3.6.2 in /usr/local/lib/python2.7/dist-packages (from docker-registry-core>=2,<3->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking iso8601>=0.1.9 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading iso8601-0.1.10.tar.gz
  Running setup.py (path:/tmp/pip_build_root/iso8601/setup.py) egg_info for package iso8601
    
Requirement already satisfied (use --upgrade to upgrade): requests>=1.1 in /usr/local/lib/python2.7/dist-packages (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking stevedore>=0.14 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading stevedore-1.2.0-py2.py3-none-any.whl
Downloading/unpacking Babel>=1.3 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Running setup.py (path:/tmp/pip_build_root/Babel/setup.py) egg_info for package Babel
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): lxml>=2.3 in /usr/lib/python2.7/dist-packages (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking six>=1.7.0 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking netaddr>=0.7.6 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking oslo.config>=1.2.1 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking pbr>=0.6,!=0.7,<1.0 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking PrettyTable>=0.7,<0.8 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
  Downloading prettytable-0.7.2.tar.bz2
  Running setup.py (path:/tmp/pip_build_root/PrettyTable/setup.py) egg_info for package PrettyTable
    
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Downloading/unpacking pytz>=0a (from Babel>=1.3->python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Requirement already satisfied (use --upgrade to upgrade): pip in /usr/lib/python2.7/dist-packages (from pbr>=0.6,!=0.7,<1.0->python-keystoneclient==0.10.0->docker-registry-driver-swift==0.2.1-git)
Installing collected packages: python-keystoneclient, python-swiftclient, docker-registry-driver-swift, iso8601, stevedore, Babel, six, netaddr, oslo.config, pbr, PrettyTable, pytz
  Running setup.py install for docker-registry-driver-swift
    Skipping installation of /usr/local/lib/python2.7/dist-packages/docker_registry/__init__.py (namespace package)
    Skipping installation of /usr/local/lib/python2.7/dist-packages/docker_registry/drivers/__init__.py (namespace package)
    
    Installing /usr/local/lib/python2.7/dist-packages/docker_registry_driver_swift-0.2.1_git-py2.7-nspkg.pth
  Running setup.py install for iso8601
    
  Running setup.py install for Babel
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    Installing pybabel script to /usr/local/bin
  Found existing installation: six 1.5.2
    Uninstalling six:
      Successfully uninstalled six
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1443, in install
    requirement.commit_uninstall()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 610, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1860, in commit
    rmtree(self.save_dir)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/pip-vxLGtP-uninstall/usr/lib/python2.7/dist-packages'

Storing debug log for failure in /root/.pip/pip.log
INFO[0135] The command [/bin/sh -c pip install /src] returned a non-zero code: 2 
```

For now I have moved to using an image built by pallet which is based includes your driver. In his Dockerfile he had to pin registry:0.7.2 and when I have now tested that version of registry directly in your Dockerfile, it builds correctly.

**Comment by bacongobbler** [comment] 2015-02-07 01:20
That's certainly odd because if I hardcode the registry to `:latest` or to `:0.9.1` it works fine for me. The automated builds on DockerHub are good too.

If you have any other insight as to why it's not working on your end, I'd be happy to PR a fix for it :)

**Comment by bacongobbler** [comment] 2015-03-25 19:38
closing as this is unreproducible and seems to work fine. If anyone else can reproduce as well as supply more information on their local setup then I'm all ears :)

**Closed by bacongobbler** 2015-03-25 19:38 UTC

**Comment by tonicmuroq** [comment] 2015-04-29 10:25
possibly because of `six`, i write `'six==1.5.2'` in my requirements and it is fixed = =
